### ISSUE TITLE
Nonfunctional on Linux (NRE spam), with included fix

### ISSUE THREAD

**Issue by DylanFrese** [Galileo88/Stock-Visual-Terrain#2]
Hello.

GenryRar posted an issue in the SVT forum thread a week ago about how they were getting NRE spam, and a black screen when they loaded their save. You linked the following Kopernicus issue: https://github.com/Kopernicus/Kopernicus/issues/158, but I'm fairly certain it's a separate issue

The issue with SVT is that the configuration files sometimes specify textures with the wrong capitalization. This happens to work on most (all?) Windows installs, because NTFS is an oddball case-insensitive filesystem. On other filesystems, case matters, and the textures fail to load.

Here are the affected lines:
```
Kerbin/Kerbin.cfg:30       steepTex = SVT/Terrain/cliffface3_00
Kerbin/Kerbin.cfg:31       steepBumpMap = SVT/Terrain/cliffface3_01
Kerbin/Kerbin.cfg:34       lowTex = SVT/Terrain/grass00
Kerbin/Kerbin.cfg:40       midTex = SVT/Terrain/grass00
Kerbin/Kerbin.cfg:35       lowBumpMap = SVT/Terrain/grass01
Kerbin/Kerbin.cfg:41       midBumpMap = SVT/Terrain/grass01
Kerbin/Kerbin.cfg:46       highTex = SVT/Terrain/noise00
Kerbin/Kerbin.cfg:47       highBumpMap = SVT/Terrain/noise01
Eve/Gilly.cfg:33           lowTex = SVT/Terrain/mun00
Eve/Gilly.cfg:39           midTex = SVT/Terrain/mun00
Eve/Gilly.cfg:45           highTex = SVT/Terrain/mun00
Eve/Gilly.cfg:34           lowBumpMap = SVT/Terrain/mun01
Eve/Gilly.cfg:40           midBumpMap = SVT/Terrain/mun01
Eve/Gilly.cfg:46           highBumpMap = SVT/Terrain/mun01
Eve/Gilly.cfg:202          mainTex = SVT/Terrain/rock00

Eve/Eve.cfg:12             texture = SVT/Eve/PluginData/eve2_00.png
Eve/Eve.cfg:84             map = SVT/Eve/PluginData/eve2_00.png

Sun/Sun.cfg:18             SVT/sun/sun.png
```

And the solution:
  * Substitute `Terrain` with `terrain` in **Kerbin.cfg** and **Gilly.cfg**
  * Substitute `sun` with `Sun` in **Sun.cfg**
  * Rename `Eve2_00.png` to `eve2_00.png`

I would make a forum post, but I refuse to make a Curse account.

**Comment by ManuGithubSteam** [comment]
Hi 
I use Linux and i have the same problem. I will try your fix and report back! Thanks!

I fixed the issue for SVT but there are also problems with SVE and scatterer i assume. 
However, this fixes SVT under Linux for me.

EDIT: I found the scatter issue: Its symlinks! KSP does not work with them :-( remove any symlinks and SVE does load without a hinch.

SVT still neds to be fixed tho...

Have fun.

[GameData_New.zip](https://github.com/Galileo88/Stock-Visual-Terrain/files/839691/GameData_New.zip)

![screenshot_20170313_230319](https://cloud.githubusercontent.com/assets/3456994/23877197/642df348-0841-11e7-9ba8-618332dd9799.png)

**Comment by Galileo88** [comment]
Thank you guys for the help. I applied the fixes for SVT although, I only had to fix the "Terrain to terrain". Everything else was already fixed so it makes me wonder, what version are you guys using and where did you download it from? I hope CKAN isn't some how using an outdated version...

EDIT: It just clicked for me that you guys are using the mac and linux version.. I apparently didnt apply these fixes to that version for whatever reason.. not important now as i have figured out how to allow SVT to play nice with dds textures and OpenGl. All the fixes above are in the latest update

**Comment by ManuGithubSteam** [comment]
Hello Galileo,

Well there are two types of files in Ckan:

SVT High Res / Med Res / Low Res
and 
SVT for Mac and Linux,

I assume the SVT High Res and the Linux  Mac files are the same ? Why are there different files ?
Version of the Mac Linux version is: 202

Also in SVT Linux Mac there is one PNG file missing in the folders PQS something. I dont know anymore, sorry. But it has blanks in the filename if that helps. But it seems to work. if i had to guess i would say its a shader thing but im not sure.

BTW: My fixed gamefiles where fixed with a purebasic program my flatmate wrote and it did find more errors than Dylan found. Also they should work with windows too.

Thanks!

**Comment by DylanFrese** [comment]
@Galileo88 You've said you figured it out, but if it still matters I downloaded the Mac/Linux version from GitHub, as linked in the forum thread. I do not use CKAN.

To find the issue, I did a bisect of my mods, and then, on a hunch, `grep`ed the files in SVT for things that look like paths, and output the ones that didn't exist on the filesystem.

**Comment by Darael** [comment]
Sed one-liner to provide a temporary fix while we wait for a release containing it, since 2.0.3 had to be pulled: `sed -i -e 's_SVT/Terrain_SVT/terrain_' -e 's_SVT/sun_SVT/Sun_' -e "s/eve2_00.png/Eve2_00.png/" /path/to/ksp/GameData/SVT/{Kerbin/Kerbin.cfg,Eve/*.cfg,Sun/Sun.cfg}` (changes references to Eve texture, rather than renaming the file, to avoid any issues with duplication when someone eventually unpacks a later release over the top.  Because that will happen eventually, inevitably)
